account_id = "9e3485a8eec4b4551fa8cd28376bec5c"
name = "saveechi"
type = "webpack"
route = ""
workers_dev = true

[site]
bucket = "./dist"
entry-point = "workers-site"


[env.production]
# The ID of your domain you're deploying to
zone_id = "3a1ff58115eea2b8722f62c2e3702d58"

